kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-log-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi



#Let us claim some of that storage for our application. Create a Persistent Volume Claim with the given specification.
#
#Volume Name: claim-log-1
#Storage Request: 50Mi
#Access Modes: ReadWriteOnce