kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 500Mi

#Let's fix that. Create a new PersistentVolumeClaim by the name of local-pvc that should bind to the volume local-pv.
#
#
#Inspect the pv local-pv for the specs.
#
#
#CheckCompleteIncomplete
#PVC: local-pvc
#Correct Access Mode?
#Correct StorageClass Used?
#PVC requests volume size = 500Mi?